-- /home/markob/markob.dev/src/markob.sdr/metadata.gif.lua
return {
    ["annotations"] = {},
    ["bbox"] = {},
    ["doc_pages"] = 2,
    ["doc_path"] = "/home/markob/markob.dev/src/markob.gif",
    ["doc_props"] = {},
    ["flipping_scroll_mode"] = false,
    ["flipping_zoom_mode"] = "page",
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["inverse_reading_order"] = false,
    ["last_page"] = 1,
    ["page_overlap_style"] = "dim",
    ["page_positions"] = {},
    ["panel_zoom_enabled"] = false,
    ["partial_md5_checksum"] = "4300406aa4295fe64b5f709a298bec3c",
    ["percent_finished"] = 0.5,
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["summary"] = {
        ["modified"] = "2025-11-30",
        ["status"] = "reading",
    },
    ["toc_ticks_ignored_levels"] = {},
    ["zoom_mode"] = "contentwidth",
}
